---
title: "Lists - In Class Exercises"
author: "Angelica Gamboa"
date: "DATA 2401"
output: html_document
---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
cards <- list(
  suit = "hearts",
  face = "king",
  value = 13
)
cards
```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
deck <- list(
  suits = c("hearts", "diamonds", "clubs", "spades"),
  faces = c("2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Queen", "King", "Ace"),
  values = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1)
)
deck

```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")
Newlist$a <- Newlist$a + 1
```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will give all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")
b$a[-2]
b$a[b$a>7]
```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")
x[["z"]] <- "NewItem"
```
